# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.py'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import main2
from PyQt5 import QtCore, QtGui, QtWidgets
from service import service
import main
from PyQt5.QtWidgets import *

class Ui_login(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(630, 337)
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.UserNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UserNameEdit.setGeometry(QtCore.QRect(330, 110, 201, 31))
        self.UserNameEdit.setObjectName("UserNameEdit")
        self.PassWordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PassWordEdit.setGeometry(QtCore.QRect(330, 150, 201, 31))
        self.PassWordEdit.setObjectName("PassWordEdit")

        self.Username = QtWidgets.QLabel(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(280, 110, 54, 31))
        self.Username.setObjectName("Username")

        self.pwd = QtWidgets.QLabel(self.centralwidget)
        self.pwd.setGeometry(QtCore.QRect(280, 150, 54, 31))
        self.pwd.setObjectName("PassWord")




        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(330,190, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        # self.AdministratorButton = QtWidgets.QRadioButton(self.centralwidget)
        # self.AdministratorButton.setGeometry(QtCore.QRect(330, 190, 89, 21))
        # self.AdministratorButton.setObjectName("AdministratorButton")
        # self.UserButton = QtWidgets.QRadioButton(self.centralwidget)
        # self.UserButton.setGeometry(QtCore.QRect(420, 190, 89, 21))
        # self.UserButton.setObjectName("UserButton")
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setGeometry(QtCore.QRect(330, 220, 75, 23))
        self.LoginButton.setObjectName("LoginButton")
        self.QuitButton = QtWidgets.QPushButton(self.centralwidget)
        self.QuitButton.setGeometry(QtCore.QRect(420, 220, 75, 23))
        self.QuitButton.setObjectName("QuitButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 80, 191, 171))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./img/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 23))
        self.menubar.setObjectName("menubar")
        login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

        # 单击“登录”按钮执行登录操作
        self.LoginButton.clicked.connect(self.openMain)

    def openMain(self):
        service.UserNameEdit = self.UserNameEdit.text()
        self.userpwd=self.PassWordEdit.text()
        index = self.comboBox.currentIndex()
        self.kind = self.comboBox.itemText(index)
        if service.UserNameEdit!="" and self.pwd!="":
            result =service.query("select * from tb_username where 用户名称=%s and 密码=%s and 类型=%s",service.UserNameEdit,self.userpwd,self.kind)

            if len(result)>0:

                if self.kind=="管理员":

                    self.m = main.Ui_MainWindow()  # 创建主窗体对象
                    self.m.show()
                    MainWindow.hide()
                else:
                    self.UserNameEdit.setText("")
                    self.PassWordEdit.setText("")
                    QMessageBox.warning(None, 'warning', '请输入正确的用户名和密码以及用户类型！')
            else:
                self.m = main2.Ui_MainWindow()  # 创建主窗体对象
                self.m.show()
                MainWindow.hide()
        else:
            QMessageBox.warning(None,'warning','请输入正确的用户名和密码以及用户类型！')


    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "登录"))
        self.Username.setText(_translate("login", "用户名："))
        self.pwd.setText(_translate("login", "密码："))
        self.label_3.setText(_translate("login", "高校学生团员管理信息系统登录页面"))
        self.comboBox.setItemText(0, _translate("user", "普通用户"))
        self.comboBox.setItemText(1, _translate("user", "管理员"))
        # self.AdministratorButton.setText(_translate("login", "管理员"))
        # self.UserButton.setText(_translate("login", "普通用户"))
        self.LoginButton.setText(_translate("login", "登录"))

        self.QuitButton.setText(_translate("login", "退出"))
        self.QuitButton.clicked.connect(Ui_login.close)

import sys
if __name__ == "__main__":
    app=QtWidgets.QApplication(sys.argv)
    MainWindow=QtWidgets.QMainWindow()
    ui=Ui_login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())