# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from 团员管理系统.service import service

class Ui_delete_2(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, delete_2):
        delete_2.setObjectName("delete_2")
        delete_2.resize(470, 247)
        self.centralwidget = QtWidgets.QWidget(delete_2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 80, 81, 41))
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(130, 80, 181, 41))
        self.name.setObjectName("name")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(320, 82, 75, 41))
        self.button.setObjectName("button")
        delete_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(delete_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 23))
        self.menubar.setObjectName("menubar")
        delete_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(delete_2)
        self.statusbar.setObjectName("statusbar")
        delete_2.setStatusBar(self.statusbar)

        self.retranslateUi(delete_2)
        QtCore.QMetaObject.connectSlotsByName(delete_2)
        self.button.clicked.connect(self.delete)

    def retranslateUi(self, delete_2):
        _translate = QtCore.QCoreApplication.translate
        delete_2.setWindowTitle(_translate("delete_2", "删除团员"))
        self.label.setText(_translate("delete_2", "输入团员姓名："))
        self.button.setText(_translate("delete_2", "删除"))

    def delete(self):
        name=self.name.text()
        if name != "":
            sql = "select 团员姓名,团员性别,团员年龄,团员所属组织,入团时间,团员职位 from tb_tg where 团员姓名 like '%" + name + "%'"
            result = service.query2(sql)
            if len(result) > 0:
                result2 = service.exec("delete from tb_tg where 团员姓名= %s", (name,))
                if result2 > 0:  # 如果结果大于0，说明删除成功

                    QMessageBox.information(None, '提示', '信息删除成功！', QMessageBox.Ok)
                else:
                    QMessageBox.information(None, '提示', '信息删除失败！', QMessageBox.Ok)

            else:
                self.name.setText("")
                QMessageBox.information(None, '提示', '您要删除的团员不存在，请重新输入！', QMessageBox.Ok)
        else:
            QMessageBox.information(None, '提示', '请重新输入要删除的团员姓名！', QMessageBox.Ok)



if __name__ == "__main__":
    app=QtWidgets.QApplication(sys.argv)
    MainWindow=QtWidgets.QMainWindow()
    ui=Ui_delete_2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
