# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tgcx.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, tycx):
        tycx.setObjectName("tycx")
        tycx.resize(791, 600)
        self.centralwidget = QtWidgets.QWidget(tycx)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 751, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 420, 81, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 420, 191, 31))
        self.lineEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 422, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 470, 75, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 468, 191, 31))
        self.lineEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 468, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 470, 81, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(470, 422, 191, 31))
        self.lineEdit_3.setObjectName("textEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 422, 81, 31))
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 424, 75, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(470, 470, 191, 31))
        self.lineEdit_4.setObjectName("textEdit_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(670, 472, 75, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        tycx.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(tycx)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 23))
        self.menubar.setObjectName("menubar")
        tycx.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(tycx)
        self.statusbar.setObjectName("statusbar")
        tycx.setStatusBar(self.statusbar)

        self.retranslateUi(tycx)
        QtCore.QMetaObject.connectSlotsByName(tycx)
        # 表格禁止编辑
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

    def retranslateUi(self, tycx):
        _translate = QtCore.QCoreApplication.translate
        tycx.setWindowTitle(_translate("tycx", "团员查询"))
        self.label.setText(_translate("tycx", "输入团员姓名:"))
        self.pushButton.setText(_translate("tycx", "查询"))
        self.pushButton_2.setText(_translate("tycx", "查询"))
        self.label_2.setText(_translate("tycx", "输入团组织:"))
        self.label_3.setText(_translate("tycx", "输入入团时间:"))
        self.label_4.setText(_translate("tycx", "输入团员性别:"))
        self.pushButton_3.setText(_translate("tycx", "查询"))
        self.pushButton_4.setText(_translate("tycx", "查询"))
